apiVersion: v1
kind: Secret
metadata:
    name: tierlist-secrets
    namespace: tierlist
type: Opaque
stringData:
    DISCORD_CLIENT_ID: ENC[AES256_GCM,data:kRyzWSuchPpaR3IjD3kwdp9WDw==,iv:TfV3/7tRcGlUsek9bLS+cQuh8vc47iJYyVkg/WdPddE=,tag:W54VDOktEHhjoFKNl+IrpQ==,type:str]
    DISCORD_CLIENT_SECRET: ENC[AES256_GCM,data:daBL9dPfZsq3GOCG4eRF6m80seYdeq5B7wPAXjB/vmU=,iv:O1i0LBq/ooh3Yt0D5qblf2F3MOVdIi4p1We8fnA+c+4=,tag:KQbs7yoULrM2HSlDW2Q0hw==,type:str]
    ADMIN_DISCORD_IDS: ENC[AES256_GCM,data:18E/fJjs32zrPH6xrBX//iJE,iv:ayTy83/wPV2g5jAkH4Kqbh21i+sSP1MbIDSszAHw44o=,tag:FWdbbRhGYg5NyLA+JNwh4g==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:D5Xt58Y0wGF58WRIaaiE2Pq9kUPzTNFRHMgKs2Ps4jc=,iv:Wu7BCAD6X1kW0WYqXuBw4fT8jEgpM7AiAmkps68vL4o=,tag:fpeeP9FBaat4jrebZMMHYA==,type:str]
sops:
    age:
        - recipient: age17e75hk8vvxc6zk30lt0dd34xqg5mfdgkzxzxzh4r75q50hk96egqkk25lz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIU3RQZTNiZi9henpSL2ZT
            QThOUjBRZExGa3NxVXNEVFBQaGhycE5wUTJjCk5hSGVLRDJGMzRVTW41T1A3RHBO
            akt4UDhTMDZZWk1UQU12eFlmNXJnREUKLS0tIFJwR3I4TSs4TFlJVVRuK2lmclcr
            Y2RaRm9WcEdqUXVqK3IxRVJkNHBQVmcKFmEhgJBRmeoHtYLiNJdCwBGSoplSnfkE
            k0Vct/lNJSECj+XnO9LPB6v7V+vOAnP6bMBUYdjm5k04OC/ZOL/sfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T14:08:05Z"
    mac: ENC[AES256_GCM,data:B1svVzq7Z9GernlHuuMS1oTSbN/+S1UNGYGG2d/qZRj7davTBnWvL6HQaQwClHAPyvqDb8kEnbCH7RaBvWEmRSt94EC/Kmm7UP0HtA0VrOEgI1S/YDyORuT6EtKItVWLlpCSCVBtDM8CmjwyO/RBdE4E24izI6v6x8ARQCav2Ig=,iv:mDpgXKX1z14FfDP426PRPybopEgZ46nVnXp+qR6HxSw=,tag:pT4ld4bPLFenVIfi4XLKZg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
